---
abstract: 'The great new RZL::MPD2MQTT!'
author:
  - 'Simon Elsbrock, C<< <simon at iodev.org> >>'
  - 'Simon Elsbrock <simon@iodev.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RZL-MPD2MQTT
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::MQTT: 0
  AnyEvent::Socket: 0
  JSON::XS: 0
  Sys::Syslog: 0
  YAML::Syck: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=RZL-MPD2MQTT
  license: http://www.opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/raumzeitlabor/rzl-mpd2mqtt.git
version: '0.01'
